export const jobListings = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'TechCo',
    location: 'New York, NY',
    programmingLanguage: 'JavaScript',
    description: 'Join our frontend development team and create amazing user interfaces.',
    qualification: "Bachelor's degree in Computer Science or related field.",
  },
  {
    id: 2,
    title: 'Backend Developer',
    company: 'DevCorp',
    location: 'San Francisco, CA',
    programmingLanguage: 'Node.js',
    description: 'Work on building the backend infrastructure of our applications.',
    qualification: 'Experience with Node.js and backend development.',
  },
  {
    id: 3,
    title: 'Full Stack Developer',
    company: 'CodeTech',
    location: 'Los Angeles, CA',
    programmingLanguage: 'React',
    description: 'Join our full stack development team and work on exciting projects.',
    qualification: 'Proficiency in React and experience with both frontend and backend development.',
  },
  {
    id: 4,
    title: 'UI/UX Designer',
    company: 'DesignStudio',
    location: 'Chicago, IL',
    programmingLanguage: 'HTML/CSS',
    description: 'Design user-friendly and visually appealing interfaces for our web applications.',
    qualification: 'Strong design skills and knowledge of HTML/CSS.',
  },
  {
    id: 5,
    title: 'Data Scientist',
    company: 'DataCo',
    location: 'Seattle, WA',
    programmingLanguage: 'Python',
    description: 'Utilize data to extract valuable insights and make data-driven decisions.',
    qualification: 'Experience with data analysis and Python programming.',
  },
  {
    id: 6,
    title: 'Software Engineer',
    company: 'SoftCorp',
    location: 'Boston, MA',
    programmingLanguage: 'Java',
    description: 'Join our software engineering team and work on cutting-edge projects.',
    qualification: 'Proficiency in Java and software development experience.',
  },
  {
    id: 7,
    title: 'DevOps Engineer',
    company: 'OpsTech',
    location: 'Austin, TX',
    programmingLanguage: 'Docker',
    description: 'Manage and optimize our DevOps processes using Docker and related tools.',
    qualification: 'Experience in DevOps and familiarity with Docker.',
  },
  {
    id: 8,
    title: 'Mobile App Developer',
    company: 'AppTech',
    location: 'Denver, CO',
    programmingLanguage: 'Swift',
    description: 'Develop mobile applications for iOS devices using Swift.',
    qualification: 'iOS app development experience with Swift.',
  },
  {
    id: 9,
    title: 'Product Manager',
    company: 'ProductCo',
    location: 'San Diego, CA',
    programmingLanguage: 'Product Management',
    description: 'Lead product development efforts and drive product strategy.',
    qualification: 'Product management experience and strong leadership skills.',
  },
  {
    id: 10,
    title: 'Cloud Architect',
    company: 'CloudTech',
    location: 'Atlanta, GA',
    programmingLanguage: 'AWS',
    description: 'Architect and manage cloud infrastructure using AWS services.',
    qualification: 'Experience with AWS cloud architecture.',
  },
  {
    id: 11,
    title: 'Data Engineer',
    company: 'DataTech',
    location: 'Portland, OR',
    programmingLanguage: 'SQL',
    description: 'Design and maintain data pipelines and databases using SQL.',
    qualification: 'SQL database development and data engineering experience.',
  },
  {
    id: 12,
    title: 'AI/ML Researcher',
    company: 'AI Research',
    location: 'Pittsburgh, PA',
    programmingLanguage: 'Machine Learning',
    description: 'Conduct research in artificial intelligence and machine learning.',
    qualification: 'Research experience in AI/ML and strong analytical skills.',
  },
  {
    id: 13,
    title: 'Cybersecurity Analyst',
    company: 'SecureCorp',
    location: 'Dallas, TX',
    programmingLanguage: 'Cybersecurity',
    description: 'Analyze and enhance the security of our systems and networks.',
    qualification: 'Cybersecurity expertise and knowledge of security practices.',
  },
  {
    id: 14,
    title: 'Quality Assurance Tester',
    company: 'QA Tech',
    location: 'Minneapolis, MN',
    programmingLanguage: 'Testing',
    description: 'Test software applications to ensure high quality and reliability.',
    qualification: 'QA testing experience and attention to detail.',
  },
  {
    id: 15,
    title: 'Business Analyst',
    company: 'BusinessTech',
    location: 'Philadelphia, PA',
    programmingLanguage: 'Business Analysis',
    description: 'Analyze business processes and make data-driven recommendations.',
    qualification: 'Business analysis skills and knowledge of data analysis tools.',
  },
  {
    id: 16,
    title: 'Network Engineer',
    company: 'NetworkTech',
    location: 'Miami, FL',
    programmingLanguage: 'Networking',
    description: 'Design and manage network infrastructure for optimal performance.',
    qualification: 'Network engineering expertise and network management experience.',
  },
  {
    id: 17,
    title: 'Web Developer',
    company: 'WebCo',
    location: 'Houston, TX',
    programmingLanguage: 'HTML/CSS/JavaScript',
    description: 'Develop web applications using HTML, CSS, and JavaScript.',
    qualification: 'Web development skills in HTML, CSS, and JavaScript.',
  },
  {
    id: 18,
    title: 'Database Administrator',
    company: 'DB Tech',
    location: 'Phoenix, AZ',
    programmingLanguage: 'Database Management',
    description: 'Manage and optimize databases for efficient data storage and retrieval.',
    qualification: 'Database administration experience.',
  },
  {
    id: 19,
    title: 'Machine Learning Engineer',
    company: 'ML Tech',
    location: 'Raleigh, NC',
    programmingLanguage: 'Machine Learning',
    description: 'Develop machine learning models and algorithms for various applications.',
    qualification: 'Machine learning expertise and programming skills.',
  },
  {
    id: 20,
    title: 'Frontend Developer',
    company: 'TechCo',
    location: 'New York, NY',
    programmingLanguage: 'React',
    description: 'Create interactive and responsive user interfaces using React.',
    qualification: 'React development skills and frontend experience.',
  },
];


